### ISSUE TITLE
Doesn't work together when 2 Joysticks are in use.

### ISSUE THREAD

**Issue by Hmmvee** [Mogli12/TrailerAssist#5]
Hello,

when I attached my 2 joysticks to use them in the game trailerassist stoppt to work.
When I disattached them again it's still not working.

The joysticks also have an issue with courseplay that the HUD then only opens with the right mousebutton, not with the defined one (other mouse button) but after dissattaching the joysticks again courseplay works with the correct button setting.

Is there an ifluence from the use of joysticks to the mod?

**Comment by Mogli12** [comment]
I guess you have problems in your inputBinding.xml.
